// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvyBVLokPTPU10MXPV0OzH5atldyWyLM',
    appId: '1:817097581089:web:ca14f66ad6c14d49a8f960',
    messagingSenderId: '817097581089',
    projectId: 'sukjunub-e37a8',
    authDomain: 'sukjunub-e37a8.firebaseapp.com',
    storageBucket: 'sukjunub-e37a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLO8xw1Y5tFS8qF2Qx2UOkWk8gRFWSPXk',
    appId: '1:817097581089:android:421205bd06b746e5a8f960',
    messagingSenderId: '817097581089',
    projectId: 'sukjunub-e37a8',
    storageBucket: 'sukjunub-e37a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ns0NUn_jBeoOk3PcFkng7nkXfWTevgo',
    appId: '1:817097581089:ios:11604287042de8aaa8f960',
    messagingSenderId: '817097581089',
    projectId: 'sukjunub-e37a8',
    storageBucket: 'sukjunub-e37a8.appspot.com',
    androidClientId: '817097581089-m3kdq3pqetqfoq7kr7kb0lacud985327.apps.googleusercontent.com',
    iosClientId: '817097581089-i4s32109c01svhbk77l2irv7j6qqrmeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sukjunub',
  );
}
